name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H 13.125.163.109 >> ~/.ssh/known_hosts

      - name: SSH to EC2 and perform actions
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@13.125.163.109 '
            # sudo systemctl stop your_service_name &&
            cd /home/ubuntu/2weekProject &&
            git fetch --all &&
            git reset --hard origin/main &&
            echo "DATABASE_URL=\"mysql://root:aaaa4321@express-database2.cxfgfhcxjpfl.ap-northeast-2.rds.amazonaws.com:3306/level3\"" >> .env &&
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&
            sudo apt-get install -y nodejs &&
            npm install -g yarn &&
            yarn &&
            npm install -g pm2 &&
            pm2 start /scr/app.js &&
            sudo systemctl start your_service_name
          '
