name: Deploy to EC2

on:
  push:
    branches:
      - main
      - dev

jobs:
  deploy1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY_NGINX }}" > ~/.ssh/id_rsa2
          chmod 400 ~/.ssh/id_rsa2
          ssh-keyscan -H 3.34.183.12 >> ~/.ssh/known_hosts

      - name: SSH to EC2 and perform actions
        run: |
            ssh -i ~/.ssh/id_rsa2 ubuntu@3.34.183.12 `
            # sudo systemctl stop your_service_name &&
            cd /home/ubuntu/2weekProject &&
            git fetch --all &&
            git reset --hard origin/main &&
            echo "DATABASE_URL=\"mysql://root:aaaa4321@express-database.cpjbd8npultq.ap-northeast-2.rds.amazonaws.com:3306/testfront\"" >> .env &&
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&
            sudo apt-get install -y nodejs &&
            npm install -g yarn &&
            yarn &&
            npm install -g pm2 &&
            pm2 start /scr/app.js &&
            sudo systemctl start your_service_name
            `
          
  deploy2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY_NGINX }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H 3.39.194.231 >> ~/.ssh/known_hosts

      - name: SSH to EC2 and perform actions
        run: |
            ssh -i ~/.ssh/id_rsa2 ubuntu@3.39.194.231 `
            # sudo systemctl stop your_service_name &&
            cd /home/ubuntu/2weekProject &&
            git fetch --all &&
            git reset --hard origin/main &&
            echo "DATABASE_URL=\"mysql://root:aaaa4321@express-database.cpjbd8npultq.ap-northeast-2.rds.amazonaws.com:3306/testfront\"" >> .env &&
            curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&
            sudo apt-get install -y nodejs &&
            npm install -g yarn &&
            yarn &&
            npm install -g pm2 &&
            pm2 start /scr/app.js &&
            sudo systemctl start your_service_name
            `
