# on:
#   push:
#     branches:
#       - dev
# jobs:
#   deploy1:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2
#       - name: Setup SSH
#         run: |
#           mkdir -p ~/.ssh/
#           echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
#           chmod 400 ~/.ssh/id_rsa
#           ssh-keyscan -H 43.200.171.118 >> ~/.ssh/known_hosts
#       - name: SSH to EC2 and perform actions
#         run: |
#           ssh -i ~/.ssh/id_rsa ubuntu@43.200.171.118 '
#             # sudo systemctl stop your_service_name &&
#             cd /home/ubuntu/2weekProject &&
#             git fetch --all &&
#             git reset --hard origin/dev &&
#             sudo echo "DATABASE_URL=\"mysql://root:aaaa4321@express-database.cpjbd8npultq.ap-northeast-2.rds.amazonaws.com:3306/testfront\"" >> .env &&
            
#             sudo apt-get update && sudo apt-get install -y ca-certificates curl gnupg &&
            
#             # curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg &&
#             # NODE_MAJOR=20 &&
#             # echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list &&
            
#             # sudo apt-get update && sudo apt-get install nodejs -y &&
#             # sudo npm install -g yarn &&
#             sudo yarn &&
#             sudo npm install -g pm2 &&
#             sudo pm2 kill &&
#             sudo pm2 start -f src/app.js
#             # sudo systemctl start your_service_name
#           '



name: Deploy to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa3
          chmod 400 ~/.ssh/id_rsa3
          ssh-keyscan -H 43.200.171.118 >> ~/.ssh/known_hosts

      - name: SSH to EC2 and perform actions
        run: |
                ssh -i ~/.ssh/id_rsa3 ubuntu@43.200.171.118 '
                  cd /home/ubuntu/2weekProject &&
                  git init &&
                  git remote add origin https://github.com/yjhorion/2weekProject.git &&
                  git pull origin dev &&
                  echo"DATABASE_URL=\"mysql://root:aaaa4321@express-database.cpjbd8npultq.ap-northeast-2.rds.amazonaws.com:3306/testfront\"" >> .env &&
                          
                  sudo apt-get install -y build-essential &&
                  sudo apt-get update &&
                  sudo apt-get install -y ca-certificates curl gnupg &&
                  sudo mkdir -p /etc/apt/keyrings &&
                  curl -fsSL https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key | sudo gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg &&
                          
                  NODE_MAJOR=20 &&
                  echo "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_$NODE_MAJOR.x nodistro main" | sudo tee /etc/apt/sources.list.d/nodesource.list &&
                          
                  sudo npm install -g yarn &&
                  sudo yarn &&
                  sudo npm install -g pm2 &&
                  sudp npx prisma generate &&
                  sudo pm2 start src/app.js &&
                  sudo systemctl start pm2
                '

            
                      
#   deploy2:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout repository
#         uses: actions/checkout@v2

#       - name: Setup SSH
#         run: |
#           mkdir -p ~/.ssh/
#           echo "${{ secrets.SSH_PRIVATE_KEY_NGINX }}" > ~/.ssh/id_rsa3
#           chmod 400 ~/.ssh/id_rsa3
#           ssh-keyscan -H 3.39.194.231 >> ~/.ssh/known_hosts

#       - name: SSH to EC2 and perform actions
#         run: |
#           ssh -i ~/.ssh/id_rsa3 ubuntu@3.39.194.231 '
#             cd /home/ubuntu/2weekproject &&
#             git fetch --all &&
#             git reset --hard origin/main &&
#             echo "DATABASE_URL=\"mysql://root:aaaa4321@express-database.cpjbd8npultq.ap-northeast-2.rds.amazonaws.com:3306/testfront\"" >> .env &&
#             curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash - &&
#             sudo apt-get install -y nodejs &&
#             npm install -g yarn &&
#             yarn &&
#             npm install -g pm2 &&
#             pm2 start /src/app.js &&
#             sudo systemctl start your_service_name
#             '

#             name: Deploy to EC2
